name: super_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  market:
    path: ../market
  banking:
    path: ../banking
  partner_module:
    path: ../partner_module
  dependencies:
    path: ../dependencies
  provider: ^6.0.3
  permission_handler: ^10.0.1
  
dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mobx_codegen: ^2.0.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true