name: dependencies
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: ../ui_kit
  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+5
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+1
  http: ^0.13.4
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
